[build]
  command = "npm run build"
  functions = "functions-build"
  publish = "public"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["socket.io"]

[[redirects]]
  from = "/socket.io/*"
  to = "/.netlify/functions/socketio"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[plugins]]
  package = "@netlify/plugin-functions-core"

[dev]
  framework = "#custom"
  command = "npm run dev"
  targetPort = 3000
  port = 8888
  publish = "public" 