[build]
  command = "npm run build"
  functions = "functions"
  publish = "public"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/socket.io/*"
  to = "/.netlify/functions/socketio"
  status = 200

[[plugins]]
  package = "@netlify/plugin-functions-core"

[dev]
  framework = "#custom"
  command = "npm run dev"
  targetPort = 3000
  port = 8888
  publish = "public" 